LOCAL_APP = "noteboard"

BOARD_MESSAGE_CHANEL_NAME = "MQBoardTest"
SEND_INTERVAL_SECOND = 30
ACK_TIMEOUT_SECONDS = 60
MAX_NOTE_SHOW = 200
MAX_ARCHIVED_NOTE_SHOW = 200
NOTEBOARD_ADMIN_PASSCODE = "667788"
NOTEBOARD_POST_PASSCODE = "1234"
